export const lib_error = {
  bad_request: { status: 400, code: 'bad-request' },
  file_max_size: { status: 400, code: 'file-max-size' },
  company_max_contact: { status: 400, code: 'company-max-contact' },
  invalid_token: { status: 401, code: 'invalid-token' },
  invalid_otp_code: { status: 401, code: 'invalid-otp-code' },
  code_expired: { status: 401, code: 'code-expired' },
  unauthorized: { status: 401, code: 'unauthorized' },
  invalid_password: { status: 401, code: 'invalid-password' },
  not_found: { status: 404, code: 'not-found' },
  not_found_user: { status: 404, code: 'not-found-user' },
  not_found_tenant: { status: 404, code: 'not-found-tenant' },
  not_found_contact: { status: 404, code: 'not-found-contact' },
  not_found_access: { status: 404, code: 'not-found-access' },
  not_found_file: { status: 404, code: 'not-found-file' },
  email_already_exist: { status: 409, code: 'email-already-exist' },
  phone_already_exist: { status: 409, code: 'user-phone-exist' },
  tenant_is_required: { status: 422, code: 'tenant-is-required' },
  format_unsupported: { status: 422, code: 'format-unsupported' },
  unprocessable_entity: { status: 422, code: 'unprocessable-entity' },
  invalid_column: { status: 422, code: 'invalid-column' },
  action_not_defined: { status: 422, code: 'action-not-defined' },
  phone_is_required: { status: 422, code: 'phone-is-required' },
  internal_server_error: { status: 500, code: 'internal-server-error' },
  service_unavailable: { status: 503, code: 'service-unavailable' },
  tenant_schema_update_failed: { status: 500, code: 'tenant-schema-update-failed' },
  user_max_tenants: { status: 400, code: 'user-max-tenants' },
}
