version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: zaatot-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
